---
abstract: 'Sugar for Catalyst controller'
author:
  - 'Jan Henning Thorsen, all rights reserved.'
build_requires:
  Data::Dumper: 2.124
  ExtUtils::MakeMaker: 6.42
  Moose: 0.94
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Controller-Sugar
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.80021
  Moose: 0.94
  namespace::autoclean: 0.09
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CatalystX-Controller-Sugar
  homepage: http://search.cpan.org/dist/CatalystX-Controller-Sugar
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jhthorsen/catalystx-controller-sugar.git
version: 0.0901
