---
abstract: 'Sugar for Catalyst controller'
author:
  - 'Jan Henning Thorsen, all rights reserved.'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Controller-Sugar
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.80021
  Data::Dumper: 2
  namespace::autoclean: 0.09
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CatalystX-Controller-Sugar
  homepage: http://jhthorsen.github.com/catalystx-controller-sugar
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jhthorsen/catalystx-controller-sugar
version: 0.0701
